cab:
  t_type: 'exponential'
  t_coeff: -100

car:
  t_type: 'exponential'
  t_coeff: -100

cbrown:
  t_type: 'none'
  t_coeff: None

cw:
  t_type: 'exponential'
  t_coeff: -0.02

cdm:
  t_type: 'exponential'
  t_coeff: -0.01

lai:
  t_type: 'exponential'
  t_coeff: -1

ala:
  t_type: 'simple'
  t_coeff: 90

bsoil:
  t_type: 'none'
  t_coeff: None

psoil:
  t_type: 'none'
  t_coeff: None

cb:
  t_type: 'none'
  t_coeff: None

n:
  t_type: 'none'
  t_coeff: None